### PR TITLE
Make dt_cnt_minus_one and DtCount plural

### PR DESCRIPTION
**Pull request by murillo128**
all the other counters are in plural: operating_points_cnt_minus_1  TemplatesCnt FrameFdiffsCnt  TemplateFdiffsCnt fdiffsCnt....

### CODE REVIEW

**Comment by Philipel-WebRTC** [comment]
Maybe I misremember, but I thought we agreed on singular for for all counts (I'm currently working on such a PR).

**Comment by murillo128** [comment]
I was reconnecting audio, so I missed that one. I am fine either way as log
as it is consistent.

**Comment by Philipel-WebRTC** [comment]
Uploaded #188

**Comment by murillo128** [comment]
closing this then

**Pull request closed without merging**
