### PR TITLE
remove trailing semicolon from write_ns()

### PR DESCRIPTION
**Pull request by alfredh**
remove trailing semicolon

### CODE REVIEW

**Comment by alfredh** [comment]
hi guys, please take a look. There are syntax errors in the sample code.

**Comment by alvestrand** [comment]
@louquillio review?

**Review by aboba — APPROVED** [review]

**Comment by agrange** [comment]
thanks for catching this, its clearly an error so merging.

**Comment by agrange** [comment]
thanks for catching this, its clearly an error so merging the PR.

**Comment by alfredh** [comment]
thanks for merging.

**Pull request merged**
